Add check for valid output
With '//' removed in selection gives:
ValueError: After processing, structure does not have exactly one model (1) with single (58) chain Z with some residues (0).